
USE [DatabaseName]
GO
ALTER DATABASE [DatabaseName] SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE([DatabaseName_log], 1)
--ALTER DATABASE [DatabaseName] SET RECOVERY FULL WITH NO_WAIT
GO

